using System.IO;
using System.Text.Json;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Threading;
using MonoTorrent.Client;

namespace Kachalka;

public partial class MainWindow
{
    async Task<object> CheckDownloadDiagnostics(string output)
    {
        Directory.CreateDirectory(output);
        var originalLight=prefs.Light;var originalSection=section;var originalCurrent=current;
        var item=new DownloadItem{MediaTitle="Проверка загрузки · диагностический интерфейс",Name="Diagnostic fixture.mkv",Folder=Path.Combine(Preferences.DataDir,"private-smoke-folder"),Paused=true};
        var snapshot=new DownloadDiagnosticSnapshot{CapturedUtc=DateTime.UtcNow,StartedUtc=DateTime.UtcNow.AddMinutes(-2),ManagerAvailable=true,State=TorrentState.Downloading,HasMetadata=true,NetworkAvailable=null,Connections=0,SpaceCheck=new(8L*1024*1024*1024,2L*1024*1024*1024,1L*1024*1024*1024,768L*1024*1024),Trackers=[new("tracker.example","udp","Offline",Failed:true),new("tracker2.example","https","Unknown")]};
        var windows=new List<Window>();var shots=new List<object>();
        void Check(bool value,string message){if(!value)throw new Exception(message);}
        void CheckCopiedReport(bool value,Window window,string report,string message)
        {
            if(value)return;
            var notice=FindVisual<TextBlock>(window,text=>text.Name=="DownloadDiagnosisNotice")?.Text??"Notice control missing.";
            var evidence=DiagnosticReport.Redact("Copy notice: "+notice+Environment.NewLine+"Clipboard report:"+Environment.NewLine+report,
                new[]{item.Folder,prefs.Folder,Preferences.DataDir,Environment.GetFolderPath(Environment.SpecialFolder.UserProfile)});
            if(evidence.Length>8192)evidence=evidence[..8192]+Environment.NewLine+"[remaining clipboard evidence omitted]";
            throw new Exception(message+Environment.NewLine+evidence);
        }
        async Task Settle(Window window){window.UpdateLayout();await window.Dispatcher.InvokeAsync(()=>{},DispatcherPriority.ApplicationIdle);await Task.Delay(100);window.UpdateLayout();}
        Button FindButton(Window window,string name)=>FindVisual<Button>(window,b=>b.Name==name)??throw new Exception("Missing diagnostic button "+name);
        void Shot(Window window,string name)
        {
            var bitmap=new RenderTargetBitmap((int)Math.Ceiling(window.ActualWidth),(int)Math.Ceiling(window.ActualHeight),96,96,PixelFormats.Pbgra32);bitmap.Render(window);
            var encoder=new PngBitmapEncoder();encoder.Frames.Add(BitmapFrame.Create(bitmap));using var file=File.Create(Path.Combine(output,name+".png"));encoder.Save(file);
            shots.Add(new{Name=name,Width=window.ActualWidth,Height=window.ActualHeight});
        }
        try
        {
            section="Загрузки";current=null;downloads.Items.Add(item);Render();await Settle(this);
            var rowButton=FindVisual<Button>(Body,b=>AutomationProperties.GetName(b)=="Почему не скачивается?"&&ReferenceEquals(b.Tag,item))??throw new Exception("Queue diagnostics action is missing.");
            Check(rowButton.ToolTip is string tip&&tip.Contains("свободное место"),"Queue diagnostics action lacks a useful accessible tooltip.");
            // Open and close the actual row command. No synthetic peer connections
            // or UAC request are generated by this paused, isolated queue fixture.
            var rowChecked=false;Exception? rowFailure=null;
            _=Dispatcher.BeginInvoke(new Action(async()=>
            {
                await Task.Delay(100);
                var opened=Application.Current.Windows.OfType<Window>().FirstOrDefault(w=>w!=this&&w.Title.StartsWith("Почему не скачивается?",StringComparison.Ordinal));
                if(opened==null){rowFailure=new Exception("The actual diagnostics modal was not found.");return;}
                try
                {
                    windows.Add(opened);await Settle(opened);
                    var reason=FindVisual<TextBlock>(opened,t=>t.Name=="DownloadDiagnosisReason");
                    Check(reason?.Text=="Загрузка на паузе","Opening diagnostics changed or misrepresented a manual pause.");
                    FindButton(opened,"CopyDownloadDiagnosis").RaiseEvent(new RoutedEventArgs(ButtonBase.ClickEvent));
                    var copied=Clipboard.GetText();
                    CheckCopiedReport(Clipboard.ContainsText()&&copied.Contains("Диагностика загрузки")&&!copied.Contains(item.Folder),opened,copied,"The row dialog did not copy a privacy-redacted report.");
                    rowChecked=true;
                }
                catch(Exception error){rowFailure=error;}
                finally{opened.Close();}
            }));
            rowButton.RaiseEvent(new RoutedEventArgs(ButtonBase.ClickEvent));
            if(rowFailure!=null)throw rowFailure;
            Check(rowChecked,"Actual queue command did not open and complete diagnostic checks.");
            var retryCalls=0;var retryFinished=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);
            var resumeCalls=0;
            var dialog=CreateDownloadDiagnostics(item,()=>snapshot,async()=>{retryCalls++;await retryFinished.Task;},()=>{resumeCalls++;item.Paused=false;snapshot=snapshot with{Paused=false};return Task.CompletedTask;});
            windows.Add(dialog);dialog.Show();await Settle(dialog);
            var retry=FindButton(dialog,"RetryDownloadConnections");
            Check(retry.IsEnabled,"Stalled active connections do not offer an explicit retry.");
            retry.RaiseEvent(new RoutedEventArgs(ButtonBase.ClickEvent));await Task.Delay(40);
            Check(retryCalls==1&&!retry.IsEnabled,"Retry did not disable itself while reconnecting.");
            retry.RaiseEvent(new RoutedEventArgs(ButtonBase.ClickEvent));Check(retryCalls==1,"A duplicate click issued a second concurrent recovery.");
            retryFinished.SetResult();await Settle(dialog);Check(retry.IsEnabled,"Retry did not recover its action after completion.");
            foreach(var light in new[]{false,true})
            foreach(var size in new[]{("wide",600d,660d),("narrow",340d,390d)})
            {
                prefs.Light=light;ApplyTheme();dialog.Width=size.Item2;dialog.Height=size.Item3;await Settle(dialog);
                var scroll=FindVisual<ScrollViewer>(dialog,s=>AutomationProperties.GetName(s)=="Диагностика загрузки")??throw new Exception("Diagnostic scroll viewer is missing.");
                Check(scroll.ViewportWidth>200,"Diagnostic content lost readable horizontal space.");
                Check(scroll.HorizontalScrollBarVisibility==ScrollBarVisibility.Disabled,"Diagnostic dialog relies on horizontal scrolling.");
                var origin=((FrameworkElement)scroll.Content).TranslatePoint(new Point(),scroll);
                Check(origin.X>=-.5&&((FrameworkElement)scroll.Content).ActualWidth<=scroll.ViewportWidth+1,"Diagnostic content overflows the narrow scroll viewport.");
                var copy=FindButton(dialog,"CopyDownloadDiagnosis");
                var copyOrigin=copy.TranslatePoint(new Point(),dialog);
                Check(copyOrigin.X>=0&&copyOrigin.X+copy.ActualWidth<=dialog.ActualWidth+1,"Diagnostic footer action overflows horizontally.");
                copy.RaiseEvent(new RoutedEventArgs(ButtonBase.ClickEvent));
                var copied=Clipboard.GetText();
                CheckCopiedReport(copied.Contains("Состояние сети пока неизвестно")&&copied.Contains("tracker.example"),dialog,copied,"Report invented an outage or lost tracker observations.");
                Shot(dialog,"diagnostics-"+size.Item1+"-"+(light?"light":"dark"));
            }
            snapshot=snapshot with{Paused=true};item.Paused=true;
            await Task.Delay(2150);await Settle(dialog);
            Check(retry.Visibility==Visibility.Collapsed,"Paused diagnostics offer a retry that could resume the queue.");
            var resume=FindButton(dialog,"ResumeDiagnosedDownload");Check(resume.IsVisible,"Paused diagnostics lack an explicit Continue action.");
            resume.RaiseEvent(new RoutedEventArgs(ButtonBase.ClickEvent));await Settle(dialog);
            Check(resumeCalls==1&&!item.Paused,"Explicit Continue did not invoke the resume callback exactly once.");
            var result=new{RowCommand=true,CopyRedactsPaths=true,UnknownNetworkHonest=true,RetrySingleFlight=true,ExplicitResume=true,Observations="Injected UI fixture; torrent transfers and reconnects are checked separately.",Photos=shots};
            File.WriteAllText(Path.Combine(output,"download-diagnostics-checks.json"),JsonSerializer.Serialize(result,new JsonSerializerOptions{WriteIndented=true}));
            return result;
        }
        finally
        {
            foreach(var window in windows)if(window.IsVisible)window.Close();
            downloads.Items.Remove(item);prefs.Light=originalLight;ApplyTheme();section=originalSection;current=originalCurrent;Render();
        }
    }
}
