Unicode true
!define MUI_ICON "../native/Assets/app.ico"
!define MUI_UNICON "../native/Assets/app.ico"
!include "MUI2.nsh"
!include "LogicLib.nsh"
!include "x64.nsh"
!include "WinVer.nsh"
!ifndef VERSION
  !define VERSION "0.28.1"
!endif
!ifndef APP_DIR
  !error "Supply APP_DIR with the published application folder"
!endif
!ifndef APP_GLOB
  !define APP_GLOB "${APP_DIR}/*"
!endif
!ifndef UNINSTALL_SCRIPT
  !error "Supply UNINSTALL_SCRIPT generated by write-uninstall.ps1"
!endif
!ifndef OUTPUT
  !define OUTPUT "Kachalka-Setup-${VERSION}.exe"
!endif
Name "Качалка ${VERSION}"
OutFile "${OUTPUT}"
InstallDir "$LOCALAPPDATA\Programs\Kachalka"
RequestExecutionLevel user
SetCompressor /SOLID zlib
VIProductVersion "${VERSION}.0"
VIAddVersionKey /LANG=1049 "ProductName" "Качалка"
VIAddVersionKey /LANG=1049 "ProductVersion" "${VERSION}"
VIAddVersionKey /LANG=1049 "FileVersion" "${VERSION}"
VIAddVersionKey /LANG=1049 "FileDescription" "Установка Качалки"
VIAddVersionKey /LANG=1049 "LegalCopyright" "Качалка"
!define MUI_ABORTWARNING
!define MUI_FINISHPAGE_RUN "$INSTDIR\Kachalka.exe"
!define MUI_FINISHPAGE_RUN_TEXT "Запустить Качалку и завершить настройку"
!define MUI_FINISHPAGE_TEXT_LARGE
!define MUI_FINISHPAGE_TEXT "При первом запуске выбери папку для загрузок. Затем можно настроить брандмауэр и запуск вместе с Windows.$\r$\n$\r$\nНажми «Готово», чтобы открыть Качалку."
!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES
!insertmacro MUI_LANGUAGE "Russian"

; An open process/mutex must not be overwritten by a manual installation.
Function .onInit
  ${IfNot} ${RunningX64}
    MessageBox MB_OK|MB_ICONEXCLAMATION "Для Качалки нужна 64-разрядная Windows."
    Abort
  ${EndIf}
  ${IfNot} ${AtLeastWin10}
    MessageBox MB_OK|MB_ICONEXCLAMATION "Для Качалки нужна Windows 10 или новее."
    Abort
  ${EndIf}
  System::Call 'kernel32::OpenMutexW(i 0x100000, i 0, w "Local\Kachalka-Install") p .r0'
  ${If} $0 != 0
    System::Call 'kernel32::CloseHandle(p r0)'
    MessageBox MB_OK|MB_ICONEXCLAMATION "Закрой Качалку перед установкой новой версии."
    Abort
  ${EndIf}
FunctionEnd

Section "Качалка"
  SetShellVarContext current
  SetOutPath "$INSTDIR"
  File /r "${APP_GLOB}"
  CreateDirectory "$SMPROGRAMS\Качалка"
  CreateDirectory "$DESKTOP"
  CreateShortcut "$SMPROGRAMS\Качалка\Качалка.lnk" "$INSTDIR\Kachalka.exe"
  CreateShortcut "$DESKTOP\Качалка.lnk" "$INSTDIR\Kachalka.exe"
  ; Keep uninstall infrastructure outside the directory swapped by the updater.
  CreateDirectory "$LOCALAPPDATA\Kachalka\installation"
  WriteUninstaller "$LOCALAPPDATA\Kachalka\installation\Uninstall.exe"
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\Kachalka" "DisplayName" "Качалка"
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\Kachalka" "DisplayVersion" "${VERSION}"
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\Kachalka" "UninstallString" '"$LOCALAPPDATA\Kachalka\installation\Uninstall.exe"'
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\Kachalka" "InstallLocation" "$INSTDIR"
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\Kachalka" "DisplayIcon" "$INSTDIR\Kachalka.exe"
  WriteRegDWORD HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\Kachalka" "NoModify" 1
  WriteRegDWORD HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\Kachalka" "NoRepair" 1
SectionEnd

Function un.onInit
  SetShellVarContext current
  StrCpy $INSTDIR "$LOCALAPPDATA\Programs\Kachalka"
  System::Call 'kernel32::OpenMutexW(i 0x100000, i 0, w "Local\Kachalka-Install") p .r0'
  ${If} $0 != 0
    System::Call 'kernel32::CloseHandle(p r0)'
    MessageBox MB_OK|MB_ICONEXCLAMATION "Закрой Качалку перед удалением."
    Abort
  ${EndIf}
FunctionEnd

Section "Uninstall"
  !include "${UNINSTALL_SCRIPT}"
  Delete "$SMPROGRAMS\Качалка\Качалка.lnk"
  RMDir "$SMPROGRAMS\Качалка"
  Delete "$DESKTOP\Качалка.lnk"
  DeleteRegKey HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\Kachalka"
  DeleteRegValue HKCU "Software\Microsoft\Windows\CurrentVersion\Run" "Ka4alka"
  Delete "$LOCALAPPDATA\Kachalka\installation\Uninstall.exe"
  RMDir "$LOCALAPPDATA\Kachalka\installation"
  ; Settings, queue, and downloaded files are deliberately retained.
SectionEnd
